// 精选词库只用于候选发现，不生成公司名单，也不按公司收集名称。
const PAYID_SCOUT_BRAND_SIGNALS = Object.freeze({
  apple: { flag: 'STRONG_BRAND', note: '与著名品牌高度关联，同时是正常英文单词。' },
  square: { flag: 'STRONG_BRAND', note: '与著名品牌高度关联，同时是正常英文单词。' },
  stripe: { flag: 'STRONG_BRAND', note: '与著名品牌高度关联，同时是正常英文单词。' },
  target: { flag: 'STRONG_BRAND', note: '与著名品牌高度关联，同时是正常英文单词。' },
  shell: { flag: 'GENERIC_BRAND', note: '普通英文词，也被一个或多个品牌使用。' },
  orange: { flag: 'GENERIC_BRAND', note: '普通英文词，也被一个或多个品牌使用。' },
  mint: { flag: 'GENERIC_BRAND', note: '普通英文词，也被一个或多个品牌使用。' },
  paypal: { flag: 'BRAND_ONLY', note: '基本只作为特定品牌名称出现。' },
});

const PAYID_SCOUT_SEEDS = [
  { word: 'cove', category: '地理', meaning: '小海湾；安全的避风处', rarity: .95, brandability: 97, memorability: 95, pronunciation: 96, versatility: 97, commercial: 95, syllables: 1 },
  { word: 'mint', category: '植物 / 材料', meaning: '薄荷；铸币；清新感', rarity: .88, brandability: 94, memorability: 95, pronunciation: 96, versatility: 98, commercial: 89, syllables: 1 },
  { word: 'moss', category: '植物', meaning: '苔藓；柔和、自然的质感', rarity: .76, brandability: 91, versatility: 88, commercial: 86, syllables: 1 },
  { word: 'lumen', category: '科技 / 光', meaning: '流明；光通量单位', rarity: .74, brandability: 93, versatility: 93, commercial: 91, syllables: 2 },
  { word: 'orbit', category: '科技 / 地理', meaning: '轨道；围绕某物运行', rarity: .65, brandability: 91, versatility: 93, commercial: 92, syllables: 2 },
  { word: 'ember', category: '自然 / 材料', meaning: '余烬；持续的热度与能量', rarity: .68, brandability: 92, versatility: 89, commercial: 87, syllables: 2 },
  { word: 'terra', category: '地理', meaning: '土地；大地', rarity: .67, brandability: 89, versatility: 92, commercial: 88, syllables: 2 },
  { word: 'haven', category: '地理 / 建筑', meaning: '避风港；安全之所', rarity: .66, brandability: 90, versatility: 90, commercial: 88, syllables: 2 },
  { word: 'cedar', category: '植物 / 材料', meaning: '雪松；耐用的木材', rarity: .77, brandability: 88, versatility: 85, commercial: 83, syllables: 2 },
  { word: 'flint', category: '材料', meaning: '燧石；坚硬且能迸发火花', rarity: .8, brandability: 90, versatility: 87, commercial: 85, syllables: 1 },
  { word: 'north', category: '地理', meaning: '北方；方向感与探索', rarity: .55, brandability: 88, versatility: 95, commercial: 92, syllables: 1 },
  { word: 'river', category: '自然 / 地理', meaning: '河流；持续流动的路径', rarity: .54, brandability: 87, versatility: 94, commercial: 90, syllables: 2 },
  { word: 'maple', category: '植物', meaning: '枫树；温暖、稳定的自然意象', rarity: .69, brandability: 87, versatility: 86, commercial: 84, syllables: 2 },
  { word: 'pearl', category: '材料 / 文化', meaning: '珍珠；稀缺、光泽与价值', rarity: .58, brandability: 91, versatility: 90, commercial: 90, syllables: 1 },
  { word: 'linen', category: '材料', meaning: '亚麻布；自然、轻盈的材料', rarity: .73, brandability: 86, versatility: 84, commercial: 82, syllables: 2 },
  { word: 'grain', category: '材料 / 食物', meaning: '谷物；颗粒；细微质地', rarity: .74, brandability: 85, versatility: 88, commercial: 84, syllables: 1 },
  { word: 'cloud', category: '天气 / 科技', meaning: '云；云计算与轻盈感', rarity: .5, brandability: 90, versatility: 97, commercial: 94, syllables: 1 },
  { word: 'rain', category: '天气', meaning: '雨；滋养、更新与自然循环', rarity: .62, brandability: 85, versatility: 88, commercial: 84, syllables: 1 },
  { word: 'solar', category: '天气 / 科技', meaning: '太阳的；太阳能', rarity: .6, brandability: 87, versatility: 91, commercial: 92, syllables: 2 },
  { word: 'coral', category: '自然 / 颜色', meaning: '珊瑚；颜色与海洋生命', rarity: .7, brandability: 89, versatility: 87, commercial: 85, syllables: 2 },
  { word: 'olive', category: '植物 / 食物', meaning: '橄榄；和平与成熟', rarity: .61, brandability: 87, versatility: 90, commercial: 86, syllables: 2 },
  { word: 'amber', category: '材料 / 颜色', meaning: '琥珀；温暖的金黄色树脂', rarity: .7, brandability: 90, versatility: 88, commercial: 87, syllables: 2 },
  { word: 'slate', category: '材料 / 科技', meaning: '板岩；清晰、可靠的底色', rarity: .75, brandability: 87, versatility: 91, commercial: 88, syllables: 1 },
  { word: 'stone', category: '材料', meaning: '石头；稳定与长期价值', rarity: .52, brandability: 83, versatility: 92, commercial: 86, syllables: 1 },
  { word: 'brick', category: '建筑 / 材料', meaning: '砖；构建与基础', rarity: .7, brandability: 86, versatility: 90, commercial: 88, syllables: 1 },
  { word: 'villa', category: '建筑', meaning: '别墅；舒适的居所', rarity: .71, brandability: 85, versatility: 78, commercial: 80, syllables: 2 },
  { word: 'tower', category: '建筑', meaning: '塔；高度、连接与地标', rarity: .58, brandability: 86, versatility: 86, commercial: 84, syllables: 2 },
  { word: 'pixel', category: '科技', meaning: '像素；数字图像的基本单元', rarity: .66, brandability: 88, versatility: 91, commercial: 90, syllables: 2 },
  { word: 'logic', category: '科技 / 文化', meaning: '逻辑；清晰的推理结构', rarity: .62, brandability: 84, versatility: 90, commercial: 87, syllables: 2 },
  { word: 'trust', category: '金融 / 文化', meaning: '信任；可靠关系', rarity: .48, brandability: 86, versatility: 96, commercial: 94, syllables: 1 },
  { word: 'fund', category: '金融', meaning: '基金；资金；支持与资源', rarity: .69, brandability: 81, versatility: 89, commercial: 90, syllables: 1 },
  { word: 'vault', category: '建筑 / 金融', meaning: '拱顶；保险库；安全存放', rarity: .73, brandability: 89, versatility: 88, commercial: 90, syllables: 1 },
  { word: 'yield', category: '金融 / 自然', meaning: '收益；产出；让行', rarity: .72, brandability: 83, versatility: 85, commercial: 89, syllables: 1 },
  { word: 'folio', category: '文化 / 金融', meaning: '页册；作品集；账户组合', rarity: .8, brandability: 88, versatility: 83, commercial: 83, syllables: 3 },
  { word: 'verse', category: '文化', meaning: '诗行；宇宙；文本空间', rarity: .73, brandability: 90, versatility: 88, commercial: 84, syllables: 1 },
  { word: 'sonic', category: '科技 / 文化', meaning: '声音的；声波的', rarity: .59, brandability: 87, versatility: 83, commercial: 84, syllables: 2 },
  { word: 'flora', category: '植物 / 文化', meaning: '植物群；植物世界', rarity: .78, brandability: 88, versatility: 84, commercial: 82, syllables: 2 },
  { word: 'fauna', category: '动物 / 自然', meaning: '动物群；动物世界', rarity: .82, brandability: 87, versatility: 78, commercial: 78, syllables: 2 },
  { word: 'otter', category: '动物', meaning: '水獭；灵活、友好的动物意象', rarity: .79, brandability: 86, versatility: 77, commercial: 75, syllables: 2 },
  { word: 'swift', category: '动物 / 科技', meaning: '雨燕；迅速、敏捷', rarity: .57, brandability: 90, versatility: 91, commercial: 90, syllables: 1 },
  { word: 'bloom', category: '植物', meaning: '开花；增长与绽放', rarity: .55, brandability: 89, versatility: 91, commercial: 88, syllables: 1 },
  { word: 'sprout', category: '植物', meaning: '嫩芽；初创与成长', rarity: .68, brandability: 88, versatility: 86, commercial: 85, syllables: 1 },
  { word: 'apple', category: '植物 / 食物', meaning: '苹果；日常、健康与知识', rarity: .35, brandability: 94, versatility: 93, commercial: 91, syllables: 2 },
  { word: 'square', category: '几何 / 建筑', meaning: '正方形；广场；方正结构', rarity: .4, brandability: 91, versatility: 92, commercial: 92, syllables: 1 },
  { word: 'stripe', category: '材料 / 颜色', meaning: '条纹；带状标记', rarity: .44, brandability: 91, versatility: 88, commercial: 90, syllables: 1 },
  { word: 'shell', category: '自然 / 材料', meaning: '贝壳；外壳；保护层', rarity: .5, brandability: 87, versatility: 90, commercial: 88, syllables: 1 },
  { word: 'orange', category: '颜色 / 食物', meaning: '橙子；橙色；能量感', rarity: .45, brandability: 88, versatility: 93, commercial: 90, syllables: 2 },
  { word: 'target', category: '金融 / 文化', meaning: '目标；靶心；清晰方向', rarity: .42, brandability: 86, versatility: 94, commercial: 93, syllables: 2 },
  { word: 'wave', category: '天气 / 自然', meaning: '波浪；信号；起伏', rarity: .6, brandability: 89, versatility: 94, commercial: 91, syllables: 1 },
  { word: 'tide', category: '自然 / 金融', meaning: '潮汐；趋势与周期', rarity: .72, brandability: 90, versatility: 89, commercial: 87, syllables: 1 },
  { word: 'reef', category: '自然 / 地理', meaning: '礁；海洋生态与边界', rarity: .76, brandability: 88, versatility: 84, commercial: 81, syllables: 1 },
  { word: 'leaf', category: '植物', meaning: '叶；页面；轻盈的自然意象', rarity: .56, brandability: 87, versatility: 91, commercial: 86, syllables: 1 },
  { word: 'peak', category: '地理 / 金融', meaning: '顶峰；峰值', rarity: .58, brandability: 88, versatility: 92, commercial: 90, syllables: 1 },
  { word: 'beam', category: '建筑 / 光', meaning: '梁；光束；支撑与方向', rarity: .73, brandability: 88, versatility: 88, commercial: 86, syllables: 1 },
  { word: 'glow', category: '光 / 文化', meaning: '发光；温暖的光泽', rarity: .57, brandability: 90, versatility: 89, commercial: 87, syllables: 1 },
  { word: 'seed', category: '植物 / 金融', meaning: '种子；起点；种子投资', rarity: .55, brandability: 88, versatility: 93, commercial: 91, syllables: 1 },
  { word: 'root', category: '植物 / 科技', meaning: '根；基础；源头', rarity: .51, brandability: 87, versatility: 94, commercial: 90, syllables: 1 },
  { word: 'nest', category: '动物 / 建筑', meaning: '巢；安全、聚合的空间', rarity: .62, brandability: 88, versatility: 91, commercial: 87, syllables: 1 },
  { word: 'fawn', category: '动物 / 颜色', meaning: '幼鹿；柔和的浅棕色', rarity: .82, brandability: 87, versatility: 77, commercial: 75, syllables: 1 },
  { word: 'iron', category: '材料', meaning: '铁；坚固、耐久', rarity: .65, brandability: 86, versatility: 88, commercial: 86, syllables: 2 },
  { word: 'glass', category: '材料 / 建筑', meaning: '玻璃；透明与界面', rarity: .51, brandability: 84, versatility: 91, commercial: 88, syllables: 1 },
  { word: 'copper', category: '材料 / 颜色', meaning: '铜；导电、温暖的金属', rarity: .7, brandability: 87, versatility: 86, commercial: 85, syllables: 2 },
  { word: 'gold', category: '材料 / 金融', meaning: '黄金；价值与稀缺', rarity: .44, brandability: 87, versatility: 96, commercial: 95, syllables: 1 },
  { word: 'cash', category: '金融', meaning: '现金；即时价值', rarity: .38, brandability: 83, versatility: 95, commercial: 94, syllables: 1 },
  { word: 'bank', category: '金融 / 地理', meaning: '银行；岸；储存与边界', rarity: .4, brandability: 82, versatility: 96, commercial: 94, syllables: 1 },
];
const PAYID_SCOUT_CATEGORY_LABELS = Object.freeze({
  animal: '动物',
  artifact: '建筑 / 科技',
  attribute: '抽象概念',
  body: '健康 / 身体',
  cognition: '科技 / 文化',
  communication: '文化 / 媒体',
  event: '事件 / 时间',
  feeling: '文化 / 情感',
  food: '食物 / 消费',
  group: '组织 / 社会',
  location: '地理 / 建筑',
  object: '材料 / 日常',
  person: '职业 / 社会',
  phenomenon: '自然 / 天气',
  plant: '植物 / 自然',
  possession: '金融 / 资产',
  process: '科技 / 过程',
  quantity: '金融 / 数据',
  relation: '商业 / 关系',
  shape: '建筑 / 设计',
  state: '通用概念',
  substance: '材料 / 化学',
  time: '时间 / 文化',
  act: '行动 / 商业',
});

const PAYID_SCOUT_CATEGORY_SCORES = Object.freeze({
  animal: [78, 78],
  artifact: [86, 86],
  attribute: [84, 80],
  body: [78, 78],
  cognition: [88, 86],
  communication: [88, 85],
  event: [78, 78],
  feeling: [82, 80],
  food: [84, 86],
  group: [82, 82],
  location: [86, 84],
  object: [85, 84],
  person: [78, 78],
  phenomenon: [86, 84],
  plant: [84, 84],
  possession: [92, 94],
  process: [88, 88],
  quantity: [90, 90],
  relation: [88, 88],
  shape: [84, 84],
  state: [84, 80],
  substance: [84, 84],
  time: [80, 78],
  act: [88, 88],
});

function bankMeta(item, index) {
  const word = item.word;
  const vowels = (word.match(/[aeiouy]/g) || []).length;
  const clusters = (word.match(/[^aeiouy]{3,}/g) || []).length;
  const letterScore = Math.max(0, Math.min(100, 72 + Math.min(16, vowels * 5) - clusters * 10 - (/[qx]/.test(word) ? 8 : 0)));
  const rarity = Math.min(.94, .56 + (item.rank / 50000) * .34);
  const [versatility, commercial] = PAYID_SCOUT_CATEGORY_SCORES[item.categoryCode] || [82, 80];
  return {
    word,
    category: PAYID_SCOUT_CATEGORY_LABELS[item.categoryCode] || '真实英文单词',
    meaning: '真实英文单词 · ' + (PAYID_SCOUT_CATEGORY_LABELS[item.categoryCode] || '词义待人工确认'),
    rarity,
    brandability: Math.round(letterScore * .55 + 70 * .45),
    memorability: letterScore,
    pronunciation: Math.max(55, letterScore - 3),
    versatility,
    commercial,
    syllables: Math.max(1, Math.min(4, (word.match(/[aeiouy]+/g) || []).length)),
    dictionary: true,
    sourceRank: item.rank,
    bankIndex: index,
  };
}

const PAYID_SCOUT_WORD_BANK_META = PAYID_SCOUT_WORD_BANK.map(bankMeta);

const PAYID_SCOUT_FEATURED_COMPOUNDS = [
  ['riverstone', '自然 / 材料', '河流 + 石头；自然、稳定、耐久'],
  ['silverline', '金融 / 材料', '银色 + 线；清晰、精致、连续'],
  ['paystream', '金融 / 支付', '支付 + 流；连续的支付流'],
  ['cloudbridge', '科技 / 数据', '云 + 桥；连接不同系统'],
  ['brightpath', '商业 / 组织', '明亮 + 路径；清晰方向'],
  ['greenfield', '自然 / 商业', '绿色 + 田野；新空间与新机会'],
  ['northstar', '地理 / 文化', '北方 + 星；方向与长期目标'],
  ['clearvault', '金融 / 支付', '清晰 + 金库；安全与透明'],
  ['goldenharbor', '金融 / 地理', '黄金 + 港湾；价值与安全停泊'],
  ['openmarket', '金融 / 商业', '开放 + 市场；自由交易空间'],
].map(([word, category, meaning]) => ({ word, category, meaning, rarity: .86, brandability: 91, memorability: 88, pronunciation: 84, versatility: 90, commercial: 92, syllables: 3, compound: true, dictionary: false }));

const PAYID_SCOUT_WORD_MAP = new Map([
  ...PAYID_SCOUT_SEEDS,
  ...PAYID_SCOUT_FEATURED_COMPOUNDS,
  ...PAYID_SCOUT_WORD_BANK_META,
].map((item) => [item.word, item]));

const PAYID_SCOUT_WORDS = [...PAYID_SCOUT_WORD_MAP.values()].slice(0, 3000);
if (PAYID_SCOUT_WORDS.length !== 3000) throw new Error('PayID Scout word library must contain 3000 unique words: ' + PAYID_SCOUT_WORDS.length);
